
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5Mjc3NDgy","is_bot":false,"login":"JamesEllenstein","name":"James Ellenstein"},"headRefName":"jamesCourseDetailsPage","number":25,"title":"James course details page","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjU5Mjc3NDgy","is_bot":false,"login":"JamesEllenstein","name":"James Ellenstein"},"headRefName":"jamesCourseIntegration","number":24,"title":"James course integration","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-1/pull/24"},{"author":{"id":"MDQ6VXNlcjcyODQzNzYw","is_bot":false,"login":"zpr-ucsb","name":"Zach Richards"},"headRefName":"Zach-FrontendUsingBackend","number":23,"title":"Added code to interface frontend with spring-boot backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-1/pull/23"}]
